### ISSUE TITLE
broken on Neovim

### ISSUE THREAD

**Issue by Alok** [alfredodeza/pytest.vim#47] opened 2016-12-25 01:44 UTC
I think you have to modify some function calls as specified [here](https://github.com/neovim/neovim/wiki/Following-HEAD).

**Comment by Alok** [comment] 2016-12-25 01:44
More specifically, running `:Pytest file` gives this error: `E120: Using <SID> not in a script context: s:HandleOutput`.

**Comment by alfredodeza** [comment] 2016-12-27 14:07
I couldn't reproduce with the NeoVim version I had. Do you know what version are you using where this is a problem?

**Comment by Alok** [comment] 2016-12-28 00:08
I'm using the latest build from git.

**Comment by alfredodeza** [comment] 2016-12-28 14:48
@Alok and what version is that? 

This is problematic for the plugin because it is a backwards incompatible change within the same major release.

I'm considering dropping a continuous support for NeoVim if this keeps up.

**Comment by alfredodeza** [comment] 2016-12-28 16:38
The current version I am trying that works is 0.1.4, for a backwards incompatible change I am unsure how could I go around supporting both ways

**Comment by Alok** [comment] 2016-12-29 01:01
NVIM v0.2.0-211-g9009c20

**Comment by alfredodeza** [comment] 2016-12-29 14:56
I will leave this issue open, but will not fix it anytime soon since this requires to support a development version that would break whoever is using the stable one(s)

**Comment by alfredodeza** [comment] 2017-06-02 17:24
I am really struggling making this work. This used to rely on the fact that I could pass `tempfile` which is where the stdout lived:

      let s:id = jobstart(s:cmdline, {
            \ 'tempfile':  tempfile,
            \ 'on_exit':   's:HandleOutput' })

But with the new way I can't, or I am failing to find a way to pass the location of `tempfile` as an argument to `HandleOutput`.

If anyone can help propose something I would be happy to review

**Comment by alfredodeza** [comment] 2017-06-08 13:25
I think this https://github.com/alfredodeza/pytest.vim/commit/455889dcd4a69cfced3526cd838fa66636d3585c fixes it. Can you guys test it please so I can merge this?

/cc @Alok @decko

**Comment by alfredodeza** [comment] 2017-06-14 22:15
@Alok @decko ping?

**Comment by kmarius** [comment] 2017-06-25 13:14
https://github.com/alfredodeza/pytest.vim/commit/455889dcd4a69cfced3526cd838fa66636d3585c fixed the problem for me using nvim v0.2.0.

**Comment by alfredodeza** [comment] 2017-07-03 17:29
Merged 5368db5b692e42e97cb4c2a3a0f005a6b72c77eb to master. Thanks for being so patient! :)

**Closed by alfredodeza** 2017-07-03 17:29 UTC
