### ISSUE TITLE
Cannot run test classes with inner classes

### ISSUE THREAD

**Issue by sloria** [alfredodeza/pytest.vim#24] opened 2015-01-18 16:38 UTC
Test classes with inner classes fail to run.

The following code reproduces the problem:

```python
class TestFoo:
    class MyClass:
        pass

    def test_method_with_inner_class(self):
        obj = self.MyClass()
        assert isinstance(obj, object)
```

Running either `Pytest class` or `Pytest method` results in an error:

```
ERROR: not found: /Users/sloria/tmp/scratch-1421564807/t.py::MyClass
(no name '/Users/sloria/tmp/scratch-1421564807/t.py::MyClass' in any of [<Module 't.py'>])
```

I am using the latest version of pytest.vim and pytest 2.6.3.

**Comment by alfredodeza** [comment] 2015-01-19 14:51
@sloria mind checking out the `issue24` branch and see if that fixes your problem? I tried and it works for me.

**Comment by sloria** [comment] 2015-01-19 16:02
@alfredodeza Running `Pytest class` now works correctly, but `Pytest method` seems to have been broken. Here is the test class I was using: https://github.com/marshmallow-code/marshmallow/blob/7826ae0d4813772dd79a876e99cf816cb2b22642/tests/test_schema.py#L1935-2033

**Comment by alfredodeza** [comment] 2015-01-19 16:34
@sloria sorry about that, mind trying it again? I *think* this is good to go now.

**Comment by sloria** [comment] 2015-01-20 02:30
@alfredodeza Yep, seems to be working. Thanks!

**Comment by alfredodeza** [comment] 2015-01-20 13:15
Fixed with https://github.com/alfredodeza/pytest.vim/pull/25

**Closed by alfredodeza** 2015-01-20 13:15 UTC

**Comment by Spaghetti-Cat** [comment] 2016-01-14 13:33
FYI, in case @alfredodeza ever has a regression with this issue or something similar, using nested classes in py.test is not supported. Here is a line from a chat I had with one of the devs:

> 2014 Feb 26 14:03:41 <ronny> SpaghettiCat_: dont use nested classes, they dont propagate data propperly - and its not supported
